// <auto-generated />
namespace XXY.MessageCenter.DbContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FailedMessage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FailedMessage));
        
        string IMigrationMetadata.Id
        {
            get { return "201510300811291_FailedMessage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
